### ISSUE TITLE
OpenAI key field bug, it can't be reopened when backspace is push to clear all the key!

### ISSUE THREAD

**Issue by apikmeister** [0xN1/kisahari#1]
https://github.com/0xN1/kisahari/assets/92358212/9efb5c8a-e0b6-4d17-ab4d-387ab3d29999

**Comment by 0xN1** [comment]
noted! by the way the OpenAI implementation is not yet up. would be cool if we can bundle that together.

**Comment by 0xN1** [comment]
PR accepted for the fix. thanks @apikmeister 

https://github.com/0xN1/kisahari/pull/2
