### ISSUE TITLE
Bug: Infinite loading on modeltypeselector for user with no ollama install on local machine

### ISSUE THREAD

**Issue by apikmeister** [0xN1/kisahari#5]
any ollama function can't be called on machine that doesn't have ollama installed

Reproduce:

- surround with try catch (will return undefined and error if there is no ollama)
- add custom loadingstate

**Comment by apikmeister** [comment]
Feature enhancement:

- Add options for user to install model using ollama.pull (if it works)
- maybe make a dialog for it, because 
![Screenshot 2024-02-13 at 10 56 17 AM](https://github.com/0xN1/kisahari/assets/92358212/7f634522-e93c-44cd-a6d8-145b5658aa0a)

**Comment by 0xN1** [comment]
> any ollama function can't be called on machine that doesn't have ollama installed
> 
> Reproduce:
> 
> * surround with try catch (will return undefined and error if there is no ollama)
> * add custom loadingstate

thank you for pointing this out! totally missed this since i already have ollama and models installed

> Feature enhancement:
> 
> * Add options for user to install model using ollama.pull (if it works)
> * maybe make a dialog for it, because
>   ![Screenshot 2024-02-13 at 10 56 17 AM](https://private-user-images.githubusercontent.com/92358212/304281689-7f634522-e93c-44cd-a6d8-145b5658aa0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3OTM4NTcsIm5iZiI6MTcwNzc5MzU1NywicGF0aCI6Ii85MjM1ODIxMi8zMDQyODE2ODktN2Y2MzQ1MjItZTkzYy00NGNkLWE2ZDgtMTQ1YjU2NThhYTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwODUwNTJmNGMzOGU2ZGFmOThlN2M1MDA0MGQ0MDJkMjBhZTBmMDQzNGI1NDM5MDA1MGZkZmUzYWQ1MzgwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jYywsZ8XvuM0XwSQY4DolDJigzyLLbnOW4wy5iNVzRs)

yeah this one would be cool. perhaps can do similar dialog like add entry. but we still need to check if they have ollama. one more idea, the dropdown would have an empty state like: `+ add model`

this `+ add model` can be the CTA for the dialog. please open a new issue for this for enhancement.
